#QUESTION 5
ALTER TABLE logistics_Emp
ADD COLUMN TOTAL_PAYABLE_CHARGES FLOAT AFTER AMOUNT;
UPDATE logistics_Emp
SET TOTAL_PAYABLE_CHARGES = SH_CHARGES + AMOUNT;
SELECT TOTAL_PAYABLE_CHARGES FROM logistics_Emp;